# Create Project
create_project Butterfly_Acc_Functionality ./Butterfly_Acc_Functionality -part xcvu37p-fsvh2892-1-e

# Add design source
add_files -norecurse -scan_for_includes {./design/sif_add_complex_half_fp.v ./design/sif_mult_half_fp.v ./design/sif_div_half_fp.v ./design/hbm_dummy_read.v ./design/butterfly_processor.v ./design/hbm_dummy_write.v ./design/butterfly_p2s_ln_opt.v ./design/ram_2d.v ./design/hbm_top.v ./design/crossbar_comb.v ./design/butterfly_indx_generator.v ./design/sif_recip_square_half_fp.v ./design/butterfly_p2s.v ./design/butterfly_s2p_opt.v ./design/hbm.v ./design/pingpong_ram_2d.v ./design/butterfly_unit_opt.v ./design/mux_comb.v ./design/butterfly_engine_opt_control.v ./design/sif_add_complex.v ./design/sif_fifo.v ./design/hbm_auto_read.v ./design/acc_top.v ./design/data_pack.v ./design/tree_fanout_opt.v ./design/butterfly_engine_opt_comp.v ./design/butterfly_s2p.v ./design/butterfly_engine_opt.v ./design/hmb_auto_write.v ./design/bu_write_addr_generator_opt.v ./design/butterfly_engine_opt_top.v ./design/weight_buffer.v ./design/hbm_control.v ./design/ram_simple_dual.v ./design/tree_fanout_double.v ./design/layer_norm.v ./design/sif_addsub_half_fp.v ./design/reg_timing.v ./design/hmb_custom_write.v ./design/sif_sub_half_fp.v ./design/tree_fanout.v ./design/butterfly_p2s_opt.v ./design/bu_read_addr_generator_opt.v}
import_files -norecurse {./design/sif_add_complex_half_fp.v ./design/sif_mult_half_fp.v ./design/sif_div_half_fp.v ./design/hbm_dummy_read.v ./design/butterfly_processor.v ./design/hbm_dummy_write.v ./design/butterfly_p2s_ln_opt.v ./design/ram_2d.v ./design/hbm_top.v ./design/crossbar_comb.v ./design/butterfly_indx_generator.v ./design/sif_recip_square_half_fp.v ./design/butterfly_p2s.v ./design/butterfly_s2p_opt.v ./design/hbm.v ./design/pingpong_ram_2d.v ./design/butterfly_unit_opt.v ./design/mux_comb.v ./design/butterfly_engine_opt_control.v ./design/sif_add_complex.v ./design/sif_fifo.v ./design/hbm_auto_read.v ./design/acc_top.v ./design/data_pack.v ./design/tree_fanout_opt.v ./design/butterfly_engine_opt_comp.v ./design/butterfly_s2p.v ./design/butterfly_engine_opt.v ./design/hmb_auto_write.v ./design/bu_write_addr_generator_opt.v ./design/butterfly_engine_opt_top.v ./design/weight_buffer.v ./design/hbm_control.v ./design/ram_simple_dual.v ./design/tree_fanout_double.v ./design/layer_norm.v ./design/sif_addsub_half_fp.v ./design/reg_timing.v ./design/hmb_custom_write.v ./design/sif_sub_half_fp.v ./design/tree_fanout.v ./design/butterfly_p2s_opt.v ./design/bu_read_addr_generator_opt.v}
update_compile_order -fileset sources_1
set_property SOURCE_SET sources_1 [get_filesets sim_1]

# Add simulation source
add_files -fileset sim_1 -norecurse -scan_for_includes {./testbench/tb_butterfly_be32_length256.sv ./testbench/tb_butterfly_ln_sc_be32_length256.sv ./testbench/tb_fft_be32_length1024.sv ./testbench/tb_butterfly_sc_be32_length256.sv ./testbench/tb_fft_be32_length256.sv ./testbench/tb_weight_buffer.sv ./testbench/tb_butterfly_be32_length1024.sv ./testbench/tb_butterfly_be32_length512.sv ./testbench/tb_fft_be32_length512.sv ./testbench/tb_butterfly_be32_length128.sv ./testbench/tb_layer_norm.sv ./testbench/tb_fft_be32_length128.sv}
import_files -fileset sim_1 -norecurse {./testbench/tb_butterfly_be32_length256.sv ./testbench/tb_butterfly_ln_sc_be32_length256.sv ./testbench/tb_fft_be32_length1024.sv ./testbench/tb_butterfly_sc_be32_length256.sv ./testbench/tb_fft_be32_length256.sv ./testbench/tb_weight_buffer.sv ./testbench/tb_butterfly_be32_length1024.sv ./testbench/tb_butterfly_be32_length512.sv ./testbench/tb_fft_be32_length512.sv ./testbench/tb_butterfly_be32_length128.sv ./testbench/tb_layer_norm.sv ./testbench/tb_fft_be32_length128.sv}
update_compile_order -fileset sim_1
set_property top tb_butterfly_ln_sc_processor_be32_length256 [get_filesets sim_1]
set_property top_lib xil_defaultlib [get_filesets sim_1]
update_compile_order -fileset sim_1

# Create IPs

# RAM
create_ip -name blk_mem_gen -vendor xilinx.com -library ip -version 8.4 -module_name ram_naive_16_1024_1r1w
set_property -dict [list CONFIG.Component_Name {ram_naive_16_1024_1r1w} CONFIG.Memory_Type {Simple_Dual_Port_RAM} CONFIG.Assume_Synchronous_Clk {true} CONFIG.Write_Depth_A {1024} CONFIG.Operating_Mode_A {READ_FIRST} CONFIG.Operating_Mode_B {READ_FIRST} CONFIG.Enable_B {Use_ENB_Pin} CONFIG.Register_PortA_Output_of_Memory_Primitives {false} CONFIG.Register_PortB_Output_of_Memory_Primitives {false} CONFIG.Port_B_Clock {100} CONFIG.Port_B_Enable_Rate {100}] [get_ips ram_naive_16_1024_1r1w]
generate_target {instantiation_template} [get_files ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.srcs/sources_1/ip/ram_naive_16_1024_1r1w/ram_naive_16_1024_1r1w.xci]
update_compile_order -fileset sources_1
generate_target all [get_files  ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.srcs/sources_1/ip/ram_naive_16_1024_1r1w/ram_naive_16_1024_1r1w.xci]
catch { config_ip_cache -export [get_ips -all ram_naive_16_1024_1r1w] }
export_ip_user_files -of_objects [get_files ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.srcs/sources_1/ip/ram_naive_16_1024_1r1w/ram_naive_16_1024_1r1w.xci] -no_script -sync -force -quiet
create_ip_run [get_files -of_objects [get_fileset sources_1] ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.srcs/sources_1/ip/ram_naive_16_1024_1r1w/ram_naive_16_1024_1r1w.xci]
launch_runs -jobs 72 ram_naive_16_1024_1r1w_synth_1
export_simulation -of_objects [get_files ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.srcs/sources_1/ip/ram_naive_16_1024_1r1w/ram_naive_16_1024_1r1w.xci] -directory ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.ip_user_files/sim_scripts -ip_user_files_dir ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.ip_user_files -ipstatic_source_dir ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.ip_user_files/ipstatic -lib_map_path [list {modelsim=./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.cache/compile_simlib/modelsim} {questa=./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.cache/compile_simlib/questa} {ies=./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.cache/compile_simlib/ies} {xcelium=./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.cache/compile_simlib/xcelium} {vcs=./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.cache/compile_simlib/vcs} {riviera=./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.cache/compile_simlib/riviera}] -use_ip_compiled_libs -force -quiet

create_ip -name blk_mem_gen -vendor xilinx.com -library ip -version 8.4 -module_name ram_naive_16_512_1r1w
set_property -dict [list CONFIG.Component_Name {ram_naive_16_512_1r1w} CONFIG.Memory_Type {Simple_Dual_Port_RAM} CONFIG.Assume_Synchronous_Clk {true} CONFIG.Write_Depth_A {512} CONFIG.Operating_Mode_A {READ_FIRST} CONFIG.Operating_Mode_B {READ_FIRST} CONFIG.Enable_B {Use_ENB_Pin} CONFIG.Register_PortA_Output_of_Memory_Primitives {false} CONFIG.Register_PortB_Output_of_Memory_Primitives {false} CONFIG.Port_B_Clock {100} CONFIG.Port_B_Enable_Rate {100}] [get_ips ram_naive_16_512_1r1w]
generate_target {instantiation_template} [get_files ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.srcs/sources_1/ip/ram_naive_16_512_1r1w/ram_naive_16_512_1r1w.xci]
generate_target all [get_files  ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.srcs/sources_1/ip/ram_naive_16_512_1r1w/ram_naive_16_512_1r1w.xci]
catch { config_ip_cache -export [get_ips -all ram_naive_16_512_1r1w] }
export_ip_user_files -of_objects [get_files ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.srcs/sources_1/ip/ram_naive_16_512_1r1w/ram_naive_16_512_1r1w.xci] -no_script -sync -force -quiet
create_ip_run [get_files -of_objects [get_fileset sources_1] ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.srcs/sources_1/ip/ram_naive_16_512_1r1w/ram_naive_16_512_1r1w.xci]
launch_runs -jobs 72 ram_naive_16_512_1r1w_synth_1
export_simulation -of_objects [get_files ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.srcs/sources_1/ip/ram_naive_16_512_1r1w/ram_naive_16_512_1r1w.xci] -directory ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.ip_user_files/sim_scripts -ip_user_files_dir ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.ip_user_files -ipstatic_source_dir ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.ip_user_files/ipstatic -lib_map_path [list {modelsim=./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.cache/compile_simlib/modelsim} {questa=./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.cache/compile_simlib/questa} {ies=./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.cache/compile_simlib/ies} {xcelium=./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.cache/compile_simlib/xcelium} {vcs=./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.cache/compile_simlib/vcs} {riviera=./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.cache/compile_simlib/riviera}] -use_ip_compiled_libs -force -quiet

# FIFO
create_ip -name fifo_generator -vendor xilinx.com -library ip -version 13.2 -module_name naive_fifo_16b_1024
set_property -dict [list CONFIG.Component_Name {naive_fifo_16b_1024} CONFIG.Fifo_Implementation {Common_Clock_Block_RAM} CONFIG.Input_Data_Width {16} CONFIG.Output_Data_Width {16} CONFIG.Use_Embedded_Registers {false} CONFIG.Reset_Type {Asynchronous_Reset} CONFIG.Full_Flags_Reset_Value {1} CONFIG.Almost_Full_Flag {true} CONFIG.Full_Threshold_Assert_Value {1022} CONFIG.Full_Threshold_Negate_Value {1021} CONFIG.Enable_Safety_Circuit {true}] [get_ips naive_fifo_16b_1024]
generate_target {instantiation_template} [get_files ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.srcs/sources_1/ip/naive_fifo_16b_1024/naive_fifo_16b_1024.xci]
generate_target all [get_files  ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.srcs/sources_1/ip/naive_fifo_16b_1024/naive_fifo_16b_1024.xci]
catch { config_ip_cache -export [get_ips -all naive_fifo_16b_1024] }
export_ip_user_files -of_objects [get_files ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.srcs/sources_1/ip/naive_fifo_16b_1024/naive_fifo_16b_1024.xci] -no_script -sync -force -quiet
create_ip_run [get_files -of_objects [get_fileset sources_1] ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.srcs/sources_1/ip/naive_fifo_16b_1024/naive_fifo_16b_1024.xci]
launch_runs -jobs 72 naive_fifo_16b_1024_synth_1
export_simulation -of_objects [get_files ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.srcs/sources_1/ip/naive_fifo_16b_1024/naive_fifo_16b_1024.xci] -directory ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.ip_user_files/sim_scripts -ip_user_files_dir ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.ip_user_files -ipstatic_source_dir ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.ip_user_files/ipstatic -lib_map_path [list {modelsim=./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.cache/compile_simlib/modelsim} {questa=./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.cache/compile_simlib/questa} {ies=./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.cache/compile_simlib/ies} {xcelium=./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.cache/compile_simlib/xcelium} {vcs=./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.cache/compile_simlib/vcs} {riviera=./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.cache/compile_simlib/riviera}] -use_ip_compiled_libs -force -quiet

# Arithmic Half_Precision IPs
create_ip -name floating_point -vendor xilinx.com -library ip -version 7.1 -module_name half_fp_addsub
set_property -dict [list CONFIG.Component_Name {half_fp_addsub} CONFIG.A_Precision_Type {Half} CONFIG.C_Optimization {Low_Latency} CONFIG.Maximum_Latency {false} CONFIG.C_Latency {1} CONFIG.C_A_Exponent_Width {5} CONFIG.C_A_Fraction_Width {11} CONFIG.Result_Precision_Type {Half} CONFIG.C_Result_Exponent_Width {5} CONFIG.C_Result_Fraction_Width {11} CONFIG.C_Accum_Msb {32} CONFIG.C_Accum_Lsb {-24} CONFIG.C_Accum_Input_Msb {15} CONFIG.C_Mult_Usage {No_Usage} CONFIG.C_Rate {1}] [get_ips half_fp_addsub]
generate_target {instantiation_template} [get_files ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.srcs/sources_1/ip/half_fp_addsub/half_fp_addsub.xci]
generate_target all [get_files  ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.srcs/sources_1/ip/half_fp_addsub/half_fp_addsub.xci]
catch { config_ip_cache -export [get_ips -all half_fp_addsub] }
export_ip_user_files -of_objects [get_files ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.srcs/sources_1/ip/half_fp_addsub/half_fp_addsub.xci] -no_script -sync -force -quiet
create_ip_run [get_files -of_objects [get_fileset sources_1] ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.srcs/sources_1/ip/half_fp_addsub/half_fp_addsub.xci]
launch_runs -jobs 72 half_fp_addsub_synth_1
export_simulation -of_objects [get_files ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.srcs/sources_1/ip/half_fp_addsub/half_fp_addsub.xci] -directory ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.ip_user_files/sim_scripts -ip_user_files_dir ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.ip_user_files -ipstatic_source_dir ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.ip_user_files/ipstatic -lib_map_path [list {modelsim=./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.cache/compile_simlib/modelsim} {questa=./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.cache/compile_simlib/questa} {ies=./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.cache/compile_simlib/ies} {xcelium=./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.cache/compile_simlib/xcelium} {vcs=./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.cache/compile_simlib/vcs} {riviera=./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.cache/compile_simlib/riviera}] -use_ip_compiled_libs -force -quiet

create_ip -name floating_point -vendor xilinx.com -library ip -version 7.1 -module_name half_fp_sub
set_property -dict [list CONFIG.Component_Name {half_fp_sub} CONFIG.Add_Sub_Value {Subtract} CONFIG.A_Precision_Type {Half} CONFIG.C_Optimization {Low_Latency} CONFIG.Maximum_Latency {false} CONFIG.C_A_Exponent_Width {5} CONFIG.C_A_Fraction_Width {11} CONFIG.Result_Precision_Type {Half} CONFIG.C_Result_Exponent_Width {5} CONFIG.C_Result_Fraction_Width {11} CONFIG.C_Accum_Msb {32} CONFIG.C_Accum_Lsb {-24} CONFIG.C_Accum_Input_Msb {15} CONFIG.C_Mult_Usage {No_Usage} CONFIG.C_Latency {8} CONFIG.C_Rate {1}] [get_ips half_fp_sub]
generate_target {instantiation_template} [get_files ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.srcs/sources_1/ip/half_fp_sub/half_fp_sub.xci]
generate_target all [get_files  ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.srcs/sources_1/ip/half_fp_sub/half_fp_sub.xci]
catch { config_ip_cache -export [get_ips -all half_fp_sub] }
export_ip_user_files -of_objects [get_files ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.srcs/sources_1/ip/half_fp_sub/half_fp_sub.xci] -no_script -sync -force -quiet
create_ip_run [get_files -of_objects [get_fileset sources_1] ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.srcs/sources_1/ip/half_fp_sub/half_fp_sub.xci]
launch_runs -jobs 72 half_fp_sub_synth_1
export_simulation -of_objects [get_files ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.srcs/sources_1/ip/half_fp_sub/half_fp_sub.xci] -directory ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.ip_user_files/sim_scripts -ip_user_files_dir ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.ip_user_files -ipstatic_source_dir ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.ip_user_files/ipstatic -lib_map_path [list {modelsim=./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.cache/compile_simlib/modelsim} {questa=./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.cache/compile_simlib/questa} {ies=./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.cache/compile_simlib/ies} {xcelium=./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.cache/compile_simlib/xcelium} {vcs=./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.cache/compile_simlib/vcs} {riviera=./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.cache/compile_simlib/riviera}] -use_ip_compiled_libs -force -quiet

create_ip -name floating_point -vendor xilinx.com -library ip -version 7.1 -module_name half_fp_mult
set_property -dict [list CONFIG.Component_Name {half_fp_mult} CONFIG.Operation_Type {Multiply} CONFIG.A_Precision_Type {Half} CONFIG.Maximum_Latency {false} CONFIG.C_Latency {1} CONFIG.C_A_Exponent_Width {5} CONFIG.C_A_Fraction_Width {11} CONFIG.Result_Precision_Type {Half} CONFIG.C_Result_Exponent_Width {5} CONFIG.C_Result_Fraction_Width {11} CONFIG.C_Accum_Msb {32} CONFIG.C_Accum_Lsb {-24} CONFIG.C_Accum_Input_Msb {15} CONFIG.C_Mult_Usage {Full_Usage} CONFIG.C_Rate {1}] [get_ips half_fp_mult]
generate_target {instantiation_template} [get_files ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.srcs/sources_1/ip/half_fp_mult/half_fp_mult.xci]
generate_target all [get_files  ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.srcs/sources_1/ip/half_fp_mult/half_fp_mult.xci]
catch { config_ip_cache -export [get_ips -all half_fp_mult] }
export_ip_user_files -of_objects [get_files ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.srcs/sources_1/ip/half_fp_mult/half_fp_mult.xci] -no_script -sync -force -quiet
create_ip_run [get_files -of_objects [get_fileset sources_1] ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.srcs/sources_1/ip/half_fp_mult/half_fp_mult.xci]
launch_runs -jobs 72 half_fp_mult_synth_1
export_simulation -of_objects [get_files ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.srcs/sources_1/ip/half_fp_mult/half_fp_mult.xci] -directory ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.ip_user_files/sim_scripts -ip_user_files_dir ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.ip_user_files -ipstatic_source_dir ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.ip_user_files/ipstatic -lib_map_path [list {modelsim=./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.cache/compile_simlib/modelsim} {questa=./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.cache/compile_simlib/questa} {ies=./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.cache/compile_simlib/ies} {xcelium=./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.cache/compile_simlib/xcelium} {vcs=./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.cache/compile_simlib/vcs} {riviera=./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.cache/compile_simlib/riviera}] -use_ip_compiled_libs -force -quiet

create_ip -name floating_point -vendor xilinx.com -library ip -version 7.1 -module_name half_fp_div
set_property -dict [list CONFIG.Component_Name {half_fp_div} CONFIG.Operation_Type {Divide} CONFIG.A_Precision_Type {Half} CONFIG.C_A_Exponent_Width {5} CONFIG.C_A_Fraction_Width {11} CONFIG.Result_Precision_Type {Half} CONFIG.C_Result_Exponent_Width {5} CONFIG.C_Result_Fraction_Width {11} CONFIG.C_Accum_Msb {32} CONFIG.C_Accum_Lsb {-24} CONFIG.C_Accum_Input_Msb {15} CONFIG.C_Mult_Usage {No_Usage} CONFIG.C_Latency {16} CONFIG.C_Rate {1}] [get_ips half_fp_div]
generate_target {instantiation_template} [get_files ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.srcs/sources_1/ip/half_fp_div/half_fp_div.xci]
generate_target all [get_files  ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.srcs/sources_1/ip/half_fp_div/half_fp_div.xci]
catch { config_ip_cache -export [get_ips -all half_fp_div] }
export_ip_user_files -of_objects [get_files ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.srcs/sources_1/ip/half_fp_div/half_fp_div.xci] -no_script -sync -force -quiet
create_ip_run [get_files -of_objects [get_fileset sources_1] ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.srcs/sources_1/ip/half_fp_div/half_fp_div.xci]
launch_runs -jobs 72 half_fp_div_synth_1
export_simulation -of_objects [get_files ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.srcs/sources_1/ip/half_fp_div/half_fp_div.xci] -directory ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.ip_user_files/sim_scripts -ip_user_files_dir ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.ip_user_files -ipstatic_source_dir ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.ip_user_files/ipstatic -lib_map_path [list {modelsim=./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.cache/compile_simlib/modelsim} {questa=./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.cache/compile_simlib/questa} {ies=./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.cache/compile_simlib/ies} {xcelium=./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.cache/compile_simlib/xcelium} {vcs=./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.cache/compile_simlib/vcs} {riviera=./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.cache/compile_simlib/riviera}] -use_ip_compiled_libs -force -quiet

create_ip -name floating_point -vendor xilinx.com -library ip -version 7.1 -module_name half_fp_recip_square
set_property -dict [list CONFIG.Component_Name {half_fp_recip_square} CONFIG.Operation_Type {Rec_Square_Root} CONFIG.A_Precision_Type {Half} CONFIG.C_A_Exponent_Width {5} CONFIG.C_A_Fraction_Width {11} CONFIG.Result_Precision_Type {Half} CONFIG.C_Result_Exponent_Width {5} CONFIG.C_Result_Fraction_Width {11} CONFIG.C_Accum_Msb {32} CONFIG.C_Accum_Lsb {-24} CONFIG.C_Accum_Input_Msb {15} CONFIG.C_Mult_Usage {No_Usage} CONFIG.C_BRAM_Usage {Full_Usage} CONFIG.C_Latency {5} CONFIG.C_Rate {1}] [get_ips half_fp_recip_square]
generate_target {instantiation_template} [get_files ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.srcs/sources_1/ip/half_fp_recip_square/half_fp_recip_square.xci]
generate_target all [get_files  ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.srcs/sources_1/ip/half_fp_recip_square/half_fp_recip_square.xci]
catch { config_ip_cache -export [get_ips -all half_fp_recip_square] }
export_ip_user_files -of_objects [get_files ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.srcs/sources_1/ip/half_fp_recip_square/half_fp_recip_square.xci] -no_script -sync -force -quiet
create_ip_run [get_files -of_objects [get_fileset sources_1] ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.srcs/sources_1/ip/half_fp_recip_square/half_fp_recip_square.xci]
export_simulation -of_objects [get_files ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.srcs/sources_1/ip/half_fp_recip_square/half_fp_recip_square.xci] -directory ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.ip_user_files/sim_scripts -ip_user_files_dir ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.ip_user_files -ipstatic_source_dir ./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.ip_user_files/ipstatic -lib_map_path [list {modelsim=./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.cache/compile_simlib/modelsim} {questa=./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.cache/compile_simlib/questa} {ies=./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.cache/compile_simlib/ies} {xcelium=./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.cache/compile_simlib/xcelium} {vcs=./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.cache/compile_simlib/vcs} {riviera=./Butterfly_Acc_Functionality/Butterfly_Acc_Functionality.cache/compile_simlib/riviera}] -use_ip_compiled_libs -force -quiet
write_project_tcl -help